---
abstract: 'Perl extension for displaying a progress indicator on a terminal. '
author:
  - 'Klaus Eichner <klaus03@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Term-Sk
requires:
  Exporter: '0'
  Fcntl: '0'
  Time::HiRes: '0'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/klaus03/Term-Sk
  repository: https://github.com/klaus03/Term-Sk.git
version: '0.17'
